language: cpp

env:
  global:
    - MAKEFLAGS="-j 2"

addons:
  apt:
    sources:
    - sourceline: 'ppa:team-gcc-arm-embedded/ppa'
    packages:
    - gcc-arm-embedded
    - libfltk1.3-dev

matrix:
  include:
    - env: PLATFORM=device EXT=elf
    - env: PLATFORM=simulator EXT=elf
    - env: PLATFORM=simulator EXT=elf TOOLCHAIN=host-clang
    - env: PLATFORM=blackbox EXT=bin QUIZ_USE_CONSOLE=1

os: linux
script:
- set -e
- make clean && make epsilon.$EXT test.$EXT
- if [ "$PLATFORM" = "blackbox" ]; then build/release/blackbox/test.$EXT; PLATFORM=blackbox make integration_tests; fi
